services:
  - type: web
    name: urlfinder
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    autoDeploy: true
